// app/articles/page.tsx
"use client";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { html2Markdown, Markdown } from "@/components/markdown";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useCompletion } from "@ai-sdk/react";
import { Loader2, Send, Trash2 } from "lucide-react";
import { useMemoizedFn } from "ahooks";
import { KeyboardEventHandler, useState } from "react";
import pageStyle from "./page.module.css";

const languageOptions = [
  {
    value: "zh",
    label: "简体中文",
  },
  {
    value: "en",
    label: "English",
  },
];

const inputMatch: Record<string, (str: string) => boolean> = {
  zh: (str: string) => {
    const chineseRegex = /[\u4e00-\u9fa5]/g;
    const matches = str.match(chineseRegex);
    if (!matches) return false;
    return matches.length / str.length > 0.8;
  },
  en: (str: string) => {
    const englishRegex = /[a-zA-Z]/g;
    const matches = str.match(englishRegex);
    if (!matches) return false;
    return matches.length / str.length > 0.8;
  },
};

const Page: React.FC = () => {
  const [language, setLanguage] = useState<string>("zh");

  const handlePaste = useMemoizedFn(async () => {
    await new Promise((resolve) => setTimeout(resolve, 60));
    handleTranslate();
  });

  const editor = useEditor({
    extensions: [StarterKit],
    editorProps: {
      attributes: {
        class: cn(
          "prose prose-sm dark:prose-invert prose-code:text-sm max-w-none",
          pageStyle.editorProse,
        ),
      },
    },
    immediatelyRender: false,
    onPaste: handlePaste,
    autofocus: true,
  });

  const { completion, isLoading, complete } = useCompletion({
    api: "/translate/api/translate",
  });

  const handleTranslate = async () => {
    const text = editor?.getText().trim();
    if (!text) return;
    const body = { language };
    if (language === "zh" && inputMatch.zh(text)) {
      body.language = "en";
      setLanguage("en");
    } else if (language === "en" && inputMatch.en(text)) {
      body.language = "zh";
      setLanguage("zh");
    }
    const htmlContent = editor?.getHTML();
    if (!htmlContent) return;
    complete(html2Markdown(htmlContent), {
      body,
    });
  };

  const handleClickEditor = () => {
    if (!editor?.isFocused) editor?.commands.focus();
  };

  const handleKeyDown: KeyboardEventHandler<HTMLElement> = (event) => {
    if (event.key === "Enter") handleTranslate();
  };

  return (
    <div className="flex gap-3 px-3 pt-1 pb-4">
      <section className="min-w-0 flex-1">
        <article
          className={cn(
            "mb-3 rounded-md transition",
            "border-gray-200 focus-within:border-blue-500",
            "dark:border-gray-500 dark:focus-within:border-blue-500",
            pageStyle.editor,
          )}
          onClick={handleClickEditor}
          onKeyDown={handleKeyDown}
        >
          <EditorContent editor={editor} />
        </article>
        <div className="mb-3 flex flex-wrap justify-end gap-3">
          <Select value={language} onValueChange={setLanguage}>
            <SelectTrigger className={pageStyle.languageSelect}>
              <SelectValue placeholder="请选择目标语言" />
            </SelectTrigger>
            <SelectContent>
              {languageOptions.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <p className="flex-1" />
          <Button
            variant="secondary"
            title="清空内容"
            onClick={() => editor?.commands.clearContent()}
          >
            <Trash2 />
          </Button>
          <Button onClick={handleTranslate}>
            <Send />
            开始翻译
          </Button>
        </div>
      </section>
      <section className="min-w-0 flex-1">
        <Markdown content={completion} />
        {isLoading ? (
          <p className="my-4">
            <Loader2 size={20} className="animate-spin" />
          </p>
        ) : null}
      </section>
    </div>
  );
};

export default Page;

// src/pages/articles.vue
<script setup lang="ts">
import StarterKit from "@tiptap/starter-kit";
import { Editor, EditorContent } from "@tiptap/vue-3";
import { v7 as uuid } from "uuid";
import { onMounted, reactive, ref, shallowRef } from "vue";
import AppHeader from "@/components/AppHeader.vue";
import HtmlContent from "@/components/HtmlContent.vue";
import { socket } from "@/utils/socket";

const loading = ref(false);

const effects: (() => unknown)[] = [];
const clearEffects = () => {
  effects.forEach((fn) => fn());
  effects.length = 0;
};

const resultText = ref("");

const startTranslate = async () => {
  await new Promise((resolve) => setTimeout(resolve, 60));
  const key = uuid();
  const htmlText = editor.value?.getHTML();
  if (!htmlText) return;
  request.text = htmlText;
  loading.value = true;
  clearEffects();
  socket().emit("translation", {
    ...request,
    key,
  });
  const handler = (response: Record<string, any>) => {
    const { text, finished } = response;
    if (finished) loading.value = false;
    resultText.value = text;
  };
  socket().on(key, handler);
  effects.push(() => socket().off(key, handler));
};

const languageOptions = [
  {
    value: "zh",
    label: "简体中文",
  },
  {
    value: "en",
    label: "English",
  },
];

const request = reactive({
  text: "",
  language: "zh",
});

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === "Enter" && !e.ctrlKey) return startTranslate();
};

const editor = shallowRef<Editor>();

onMounted(() => {
  editor.value = new Editor({
    autofocus: true,
    extensions: [StarterKit],
    editorProps: {
      attributes: {
        class: "prose prose-sm dark:prose-invert prose-code:text-sm",
      },
    },
  });
});

const handleClickEditor = ({ target }: MouseEvent) => {
  if (!(target instanceof Element)) return;
  const prose = target.closest(".prose");
  if (prose) return;
  editor.value?.commands.focus();
};

const clearContent = () => {
  editor.value?.commands.clearContent();
};

const handlePaste = async () => {
  await startTranslate();
};
</script>

<template>
  <AppHeader class="justify-center px-2 pt-1" />
  <main class="mt-4 flex gap-5 px-4 pb-6">
    <div class="min-w-0 flex-1">
      <article
        class="editor rounded-md border-gray-200 focus-within:border-blue-500 dark:border-gray-500 dark:focus-within:border-blue-500"
        @keydown="handleKeyDown"
        @paste="handlePaste"
        @click="handleClickEditor"
      >
        <EditorContent class="markdown" :editor="editor" />
      </article>
      <div class="mb-3 flex flex-wrap justify-end gap-3">
        <USelect
          v-model="request.language"
          style="width: 8rem"
          :items="languageOptions"
          value-key="value"
        />
        <p class="flex-1" />
        <UButton
          square
          title="清空内容"
          color="neutral"
          icon="i-tabler-clear-all"
          @click="clearContent"
        />
        <UButton icon="i-tabler-run" @click="startTranslate">
          开始翻译
        </UButton>
      </div>
    </div>
    <div class="markdown min-w-0 flex-1">
      <HtmlContent
        :content="resultText"
        class="prose dark:prose-invert prose-code:text-base mb-2"
      />
      <UIcon
        v-if="loading"
        name="i-tabler-loader-2"
        style="font-size: 20px"
        class="animate-spin"
      />
    </div>
  </main>
</template>

<style scoped>
.markdown :deep(.prose) {
  max-width: none;
}
.markdown :deep(.prose:focus) {
  outline: none;
}

.editor {
  border-width: 2px;
  border-style: dashed;
  min-height: 20rem;
  margin-bottom: 0.8rem;
  padding: 0.6rem 0.8rem;
}
</style>
